### PR TITLE
Move bandit to same job

### PR DESCRIPTION
**Pull request by enescakir**
When it's in separate job, it takes ~30 seconds and GitHub counts it as 1 billable minute. 

When it's at the end of the linter job, whole linter action takes ~40 seconds and GitHub counts it as 1 billable minute. 

This workflow runs 300-400 times per month, so this PR will save 300-400 billable minutes.
Screenshot 2023-03-01 at 20 04 19

### CODE REVIEW

**Review by omeraksoy1 — APPROVED** [review]
LGTM

**Review by mdegis — APPROVED** [review]
anything to reduce the cost 😢 

however, pls note that current bandit action is cooler, at least it can comment on PRs (and open source)...

**Review by iKlotho — APPROVED** [review]

**Comment by mfnd** [comment]
What was the cost of 300 minutes?

**Comment by enescakir** [comment]
> What was the cost of 300 minutes?

We have 3000 minutes credit monthly. After that, we need to insert coin 🪙

**Comment by mfnd** [comment]
> > What was the cost of 300 minutes?
> 
> We have 3000 minutes credit monthly. After that, we need to insert coin coin

So, how much coin should we insert for 300 minutes? :D

Do we use 2-core Linux machines as runners?

**Review by mfnd — APPROVED** [review]

**Pull request merged**
